name: "aline build"
on:
  push:
    branches:
      - master
      - develop

jobs:
  package:
    strategy:
      matrix:
        platform: [ ubuntu-latest,windows-latest,macos-latest ]
        node-version: [18]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # You may need to manually build you frontend manually here, unless you have configured frontend build and install commands in wails.json.
      - name: build
        if: matrix.platform == 'ubuntu-latest'
        run:  make linux
      - name: upload artifacts
        if: matrix.platform == 'ubuntu-latest'
        uses: actions/upload-artifact@v2
        with:
          name: aline-linux-amd64.zip
          path: aline

      - name: build
        if: matrix.platform == 'windows-latest'
        run:  make windows
      - name: upload artifacts
        if: matrix.platform == 'windows-latest'
        uses: actions/upload-artifact@v2
        with:
          name: aline-windows-amd64.zip
          path: aline.exe

      - name: build
        if: matrix.platform == 'macos-latest'
        run:  make macos
      - name: upload artifacts
        if: matrix.platform == 'macos-latest'
        uses: actions/upload-artifact@v2
        with:
          name: aline-darwin-amd64.zip
          path: aline
